Make grid pattern appear
w3c/wai-aria-practices pull request #112
Opened 2022-06-01 18:50 UTC by alflennik

Address issue #102.

2022-06-01 19:02 UTC, richnoah commented
@alflennik I see Grid present and the content looks good.

2022-06-01 23:13 UTC, howard-e requested changes
@alflennik looks good to me other than the comment relating to the alphabetical order on the patterns page. Good stuff!

Another thing of note is on [Data Grid Examples Page, Example 2: Sortable Data Grid With Editable Cells](https://deploy-preview-112--wai-aria-practices2.netlify.app/aria/apg/example-index/grid/datagrids), there appears to be some conflicting CSS here which is forcing the edit icon over the column line for its respective cell. But that's outside the purpose of this PR and I believe there may be an over-arching task to account for these kind of task? If not, it could be filed in a separate issue.

2022-06-01 23:13 UTC, howard-e commented on content/patterns.md
> +                      <span>Grids : Interactive Tabular Data and Layout Containers</span>
This pattern should come before `Landmarks`

2022-06-02 17:33 UTC, alflennik commented on content/patterns.md
> +                      <span>Grids : Interactive Tabular Data and Layout Containers</span>
What a great catch! I wouldn't have noticed in a million years.

2022-06-02 17:35 UTC, alflennik commented
@howard-e I decided to go ahead and fix the offending example.

2022-06-02 18:00 UTC, merged

2022-06-03 14:49 UTC, mcking65 commented
Thank you @alflennik!!!